# [Metadata]  Author  Owais Jilani

# Common Test data
tdDateFormatYyyyMmDd = "%Y-%m-%d"
tdFileFormatCSV = ".csv"

#Resolution Test Data
tdResolutionException = "Exception"
tdResolutionFurtherReview = "Further Review"
tdResolutionOther = "Other"
tdResolutionPendingInvestigation = "Pending Investigation"
tdResolutionPossibleATO = "Possible ATO"
tdResolutionPendingCallbackFromTheCustomer = "Pending call back from the customer"
tdResolutionExceptionReviewed = "Exception - Reviewed"
tdResolutionFurtherReviewReviewed = "Further Review - Reviewed"
tdResolutionNewActivity = "New Activity"

#Channels Test Data
tdChannel = "Channel"
tdChannelACHODFI = "ACHODFI"
tdChannelCheck = "Check"
tdChannelTransactionMonitoring = "Transaction Monitoring"
tdChannelWire = "Wire"

#Priority TD
tdPriorityLow = "Low"
tdPriorityMedium = "Medium"
tdPriorityHigh = "High"

tdSampleComment = "Test Case created by automation script!"
tdSampleSummary = "Test Summary"

#Status
tdStatusOpen = "Open"
tdStatusInProcess = "In Process"
tdStatusPendingReview = "Pending Review"
tdStatusEscalationReview = "Escalation Review"
tdStatusPendingReviewCompleted = "Pending Review Completed"
tdStatusEscalationReviewCompleted = "Escalation Review Completed"
tdStatusClosed = "Closed"
tdStatusActive = "Active"

#User Roles
tdRoleManager = "Manager"

#Common TexArea Data
tdAccountNotesSummary = "This is Account Notes generated by Automation Script"
tdAccountNotesCancelSummary = "This should not get Altered by Automation Script"
tdTextPara1000Characters= "In the enchanting realm of imagination, where dreams weave intricate tapestries of vibrant colors and fantastical landscapes, a whimsical journey unfolds as ethereal beings dance upon the shimmering threads of possibility, casting spells of wonder that transcend the boundaries of reality; within this kaleidoscopic tapestry, every moment becomes an intricate mosaic of emotions, from gentle whispers of nostalgia to exhilarating crescendos of unbridled joy, painting the canvas of existence with strokes of experience that traverse the spectrum of human essence. A symphony of life's melody plays in harmonious resonance with the pulsating heartbeat of the cosmos, orchestrating dance of interconnected destinies amidst the cosmic ballet of time and space. Each heartbeat is a cadence in the grand symphony of existence, echoing through the corridors of eternity, resonating with the celestial rhythm that binds the universe in a celestial embrace.Sentence Limit Reached that is 1000 Character.OWAIS"
tdAppendBeyondLimit = "$BEYOND_LIMIT$"

# Operator
tdOperatorEqualTo = "Equal To"
