# [Metadata]  Author  Owais Jilani
searchInput = "css:[name='q']"
oBmsLink ="(//a[@jsname='UWckNb'])[2]"
oButton = "//button"
oUsername = "id=user-name"
oPassword = "id=password"
oLoginButton = "id=login-button"
validUsername = "standard_user"
validPassword = "secret_sauce"
invalidUsername = "invalid_user"
invalidPwd = "invalid_password"
shoppingCartBadge = "xpath=//span[@class='shopping_cart_badge']"
addToCart = "xpath=//button[text()='Add to cart']"
removeButton = "xpath=//button[text()='Remove']"
shoopingCartLink = "xpath=//a[contains(@class, 'shopping_cart_link')]"
finishButton = "id=finish"
oFirstName = "id=first-name"
oLastname = "id=last-name"
oPostalCode = "id=postal-code"
ocheckoutButton = "id=checkout"
ocancelButton = "id=cancel"
oContinueButton = "id=continue"
oAppLogo = "//img[@class='logoImg']"
oLogo = "//img[@alt='logo']"
oSignInButton = "xpath://*[@id='loginForm:trylogin']"
oLoginUsernameInput = "id:user-name"
oLoginPasswordInput = "id:loginForm:userpw"
oForgotPwdLink = "xpath://a[text()='Forgot your password?']"
oInvalidLoginMessage = "css:div#jsfErrors li"
oWaitLoader = "//div[contains(@class, '__commonLoader__')]"
oForgottonPwInput = "forgotPassword"
oSendEmail = "submit-forgot-password"
oConfirmPassword = "//input[@name='confirmPassword']"
oNewPassword = "//input[@name='newPassword']"
oChangePassword = "submit-new-password-button"
oChangePasswordSuccess = "//div[contains(@class, 'responseContent')]//span[text()='Success! Email Sent.']"
oLoginWelcomeBadge = "//header[@class='MuiStack-root css-2mn8kl']"
oTrademarkName = "//img[@class='logo']"
oProfileButton = "//body"
